services:
  - type: worker
    name: iproyal-pawns
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    startCommand: >
      /pawns-cli
      -email $PAWNS_EMAIL
      -password $PAWNS_PASSWORD
      -device-name $DEVICE_NAME
      -device-id $DEVICE_ID
      -accept-tos
